[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

  [build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"

[dev]
  command = "remix watch"
  port = 3000

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
    group = "Testing Built Site"

[[redirects]]
  from = "*"
  to = "https://www.eventbrite.com/o/befunny-60651135703"
  status = 200
